version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    hostname: ${EXTERNAL_URL}
    volumes:
      - $GITLAB_HOME/config:/etc/gitlab
      - $GITLAB_HOME/logs:/var/log/gitlab
      - $GITLAB_HOME/data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${EXTERNAL_URL}'
      TZ: Asia/Seoul

  dind:
    image: docker:dind
    restart: always
    privileged: true
    ports:
      - "2375:2375"
    environment:
      DOCKER_TLS_CERTDIR: ""
    command:
      - --storage-driver=overlay2
  runner:
    restart: always
    image: 'gitlab/gitlab-runner:latest'
    volumes:
      - $GITLAB_HOME/runner:/etc/gitlab-runner:Z
    depends_on:
      - dind
    environment:
      - DOCKER_HOST=tcp://dind:2375

  register-runner:
    restart: 'no'
    image: gitlab/gitlab-runner:latest
    depends_on:
      - dind
    environment:
      - CI_SERVER_URL=https://${EXTERNAL_URL}
      - REGISTRATION_TOKEN=${REGISTRATION_TOKEN}
    command:
      - register
      - --non-interactive
      - --locked=false
      - --name=${RUNNER_NAME}
      - --executor=docker
      - --docker-image=docker:dind
    volumes:
      - $GITLAB_HOME/runner/docker.sock:/var/run/docker.sock
      - $GITLAB_HOME/runner:/etc/gitlab-runner:Z